#!/bin/bash
set -ex

sudo yum update -y
sudo yum -y install epel-release
sudo yum -y install nginx git vim
#sudo firewall-cmd --zone=public --add-port=80/tcp
systemctl disable firewalld
sudo mkdir -p /var/www/html/js
cd /var/www/
sudo git clone https://github.com/mjastad/uptick uptick
cd uptick
sudo cp -Rvp index.html fonts css images ../html/
sudo cp -Rvp js/data.js ../html/js/
sudo chmod -R 755 /var/www/html/*
sudo setenforce 0
sudo echo "SELINUX=disabled
SELINUXTYPE=targeted" > /etc/selinux/config
#sed -ie "s\/usr\/share\/ngnix/\/var\/www\/html/" /etc/nginx/nginx.conf
sudo echo "user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    upstream nodejs {
        server @@{NodeJS_Service.address}@@:3000;
    }
    
    server {
        listen 80;
        server_name localhost;
        root ~/workspace/test/app;
    
        location / {
            try_files $uri $uri/ @nodejs;
        }
    
        location @nodejs {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_pass http://nodejs;
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    
        error_page 404 /404.html;
            location = /40x.html {
        }
    
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

}
" > /etc/nginx/nginx.conf
sudo systemctl enable nginx
sudo systemctl restart nginx
